---
version: "3.9"

# ================================================
# ANCHORS
# ================================================

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "500k"
    max-file: "20"

x-entrypoint: &default-entrypoint
  entrypoint: >
    /bin/sh -c "
      set -e
      echo Waiting TTY interaction..
      /bin/bash || exit 0
    "

# ================================================
# DEFINING SERVICES
# ================================================

services:

  algorithms:
    container_name: $CONTAINER_NAME
    env_file: .env.test
    build:
      context: $PATH_DOCKERFILE
      dockerfile: Dockerfile
    <<: *default-entrypoint
    stdin_open: true
    tty: true
    restart: on-failure
    logging: *default-logging
    networks: [ "algorithms" ]

# ================================================
# DEFINING NETWORKS
# ================================================

networks:
  algorithms:
