# =============================================================================
# BASE CONFIGURATION
# =============================================================================

version: "3.7"

# =============================================================================
# SERVICES
# =============================================================================

services:

# =============================================================================
# ALGORITHMS
# =============================================================================

  algorithms:
    container_name: ${CONTAINER_NAME}
    env_file: ./.env
    build:
      context: ./code
      dockerfile: Dockerfile
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "20"
    networks:
      - algorithms

# =============================================================================
# NETWORK
# =============================================================================

networks:
  algorithms:
    