name: Gitavscan

# Trigger the workflow on push or pull request, but only for the main branch.
#
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Run ClamAV antivurs - https://www.clamav.net
#
jobs:
  gitavscan:
    name: AV scan

    strategy:
      matrix:
        os: [ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Git AV Scan
      uses: djdefi/gitavscan@main
      continue-on-error: false
